apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: agent-pv-claim
  labels:
    app: zabbix-agent
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: storage-gcp
  resources:
    requests:
      storage: 10Gi